version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd cicd # change directory
      - chmod +x install_tf.sh configure_profile.sh apply_tf.sh # make files executable
      - ./install_tf.sh # install terraform
      - ./configure_profile.sh # configure named profile

  build:
    commands:
      - ./apply_tf.sh